/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RnD03
 */
public class Form_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Form_Menu
     */
    public Form_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuJenisBarang = new javax.swing.JMenuItem();
        MenuBarang = new javax.swing.JMenuItem();
        MenuDistributor = new javax.swing.JMenuItem();
        MenuDataPetugas = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuDataBarangMasuk = new javax.swing.JMenuItem();
        MenuDataPenjualanBarang = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        DaftarReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        MenuJenisBarang.setText("Data Jenis Barang");
        MenuJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuJenisBarangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuJenisBarang);

        MenuBarang.setText("Data Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBarang);

        MenuDistributor.setText("Data Distributor");
        MenuDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDistributorActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDistributor);

        MenuDataPetugas.setText("Data Petugas");
        MenuDataPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataPetugasActionPerformed(evt);
            }
        });
        jMenu1.add(MenuDataPetugas);

        MenuExit.setText("Exit");
        jMenu1.add(MenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        MenuDataBarangMasuk.setText("Data Barang Masuk");
        jMenu2.add(MenuDataBarangMasuk);

        MenuDataPenjualanBarang.setText("Data Penjualan Barang");
        MenuDataPenjualanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataPenjualanBarangActionPerformed(evt);
            }
        });
        jMenu2.add(MenuDataPenjualanBarang);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Report");

        DaftarReport.setText("Daftar Report");
        jMenu5.add(DaftarReport);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuJenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuJenisBarangActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDistributorActionPerformed
        // TODO add your handling code here:
        new Form_Distributor_barang().setVisible(true);
    }//GEN-LAST:event_MenuDistributorActionPerformed

    private void MenuDataPenjualanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataPenjualanBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDataPenjualanBarangActionPerformed

    private void MenuDataPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataPetugasActionPerformed
        // TODO add your handling code here:
        new Form_Petugass().setVisible(true);
    }//GEN-LAST:event_MenuDataPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DaftarReport;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuDataBarangMasuk;
    private javax.swing.JMenuItem MenuDataPenjualanBarang;
    private javax.swing.JMenuItem MenuDataPetugas;
    private javax.swing.JMenuItem MenuDistributor;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuJenisBarang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
