
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RnD03
 */
public class Form_Distributor_barang extends javax.swing.JFrame {

    private DefaultTableModel model;
     private String ID;
     private String Nama;
     private String Alamat;
     private String Kota;
     private String Emaill;
     private String Telponn;


     
    /**
     * Creates new form Form_Distributor_barang
     */
    public Form_Distributor_barang() {
        initComponents();
        loadData();
        kosong();
        setEnablefalse();
    }
    public void setEnablefalse(){
       IDDistributor.setEnabled(false);
       NamaDistributor.setEnabled(false);
       AlamatDistributor.setEnabled(false);
       KotaAsal.setEnabled(false);
       Email.setEnabled(false);
       Telpon.setEnabled(false);
    }
    public void setEnabletrue(){
       IDDistributor.setEnabled(true);
       NamaDistributor.setEnabled(true);
       AlamatDistributor.setEnabled(true);
       KotaAsal.setEnabled(true);
       Email.setEnabled(true);
       Telpon.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NamaDistributor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlamatDistributor = new javax.swing.JTextArea();
        IDDistributor = new javax.swing.JTextField();
        KotaAsal = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Telpon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        AddNew = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 225, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entri Data Distributor Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 562, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Version.0.1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel10)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 562, -1));

        jLabel2.setText("ID Distributor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, -1, -1));

        jLabel4.setText("Nama Distributor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 106, -1, -1));

        jLabel5.setText("Alamat Distributor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 143, -1, -1));

        jLabel6.setText("Kota Asal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 207, -1, -1));

        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 244, -1, -1));

        jLabel8.setText("Telpon");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 284, -1, -1));
        jPanel1.add(NamaDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 103, 370, -1));

        AlamatDistributor.setColumns(20);
        AlamatDistributor.setRows(5);
        jScrollPane1.setViewportView(AlamatDistributor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 133, -1, 60));
        jPanel1.add(IDDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 63, 130, -1));
        jPanel1.add(KotaAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 204, 370, -1));
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 244, 370, -1));
        jPanel1.add(Telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 284, 154, -1));

        jLabel9.setText("Maksimal 15 Digit");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 500, 140));

        AddNew.setText("Add New");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });
        jPanel1.add(AddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel1.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        jPanel1.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
    //membuat model
    model= new DefaultTableModel();
    
    //menghapus seluruh data
    model.getDataVector().removeAllElements();
    // memberi tahu bahwa data telah kosong
    model.fireTableDataChanged();
   
    Table.setModel(model);
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Alamat");
    model.addColumn("Kota");
    model.addColumn("Emaill");
    model.addColumn("Telponn");
   
    try{
       
        String sql = "SELECT * FROM tbldistributor";
       
        Connection c = Koneksi.getKoneksi();
        Statement s = c.createStatement();
        ResultSet r = s.executeQuery(sql);
       
        while(r.next()){
            // lakukan penelusuran baris
            model.addRow(new Object[]{
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
            });
        }
        Table.setModel(model);
    }catch(SQLException e){
        System.out.println("Terjadi Error");
    }
   
}
   private void kosong(){
       IDDistributor.setText(null);
       NamaDistributor.setText(null);
       AlamatDistributor.setText(null);
       KotaAsal.setText(null);
       Email.setText(null);
       Telpon.setText(null);
   }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String ID = IDDistributor.getText();
        String Nama= NamaDistributor.getText();
        String Alamat = AlamatDistributor.getText();
        String Kota = KotaAsal.getText();
        String Emaill = Email.getText();
        String Telponn = Telpon.getText();
        
        
        if ("".equals(ID) || "".equals(Nama) ||
                "".equals(Alamat) ||
                "".equals(Kota) || "".equals(Emaill)|| "".equals(Telponn))
        {
            JOptionPane.showMessageDialog(this,
                    "Harap Lengkapi Data",
                    "Eror", JOptionPane.WARNING_MESSAGE);
        } else {
            try{
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO tbldistributor VALUES (?,?,?,?,?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                
                p.setString(1, ID);
                p.setString(2, Nama);
                p.setString(3, Alamat);
                p.setString(4, Kota);
                p.setString(5, Emaill);
                p.setString(6, Telponn);
                
                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null,
                        "Penyimpanan Data Berhasil");
                
            }catch(SQLException e) {
                JOptionPane.showMessageDialog(this, 
                        e.getMessage());                
            }finally{
                loadData();
                kosong();
            }
    }
    }//GEN-LAST:event_SaveActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
        // TODO add your handling code here:
        setEnabletrue();
        AddNew.setEnabled(true);
    }//GEN-LAST:event_AddNewActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int i = Table.getSelectedRow();
        
        if(i == -1){
            //tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu,",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String ID = IDDistributor.getText();
        String Nama = NamaDistributor.getText();
        String Alamat = AlamatDistributor.getText();
        String Kota = KotaAsal.getText();
        String Emaill = Email.getText();
        String Telponn = Telpon.getText();
        
        try{
            Connection c = Koneksi.getKoneksi();
            
            String sql = "UPDATE tbldistributor SET NamaDistributor = ?, Alamat = ?, Kotasal = ?, Email = ?, Telpon = ? WHERE IDDistributor = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            
            p.setString(1, Nama);
            p.setString(2, Alamat);
            p.setString(3, Kota);
            p.setString(4, Emaill);
            p.setString(5, Telponn);
            p.setString(6, ID);
            
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null, "Ubah Data Berhasil");
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error" + e.getMessage());
        } finally{
            loadData();
            kosong();
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        int baris = Table.getSelectedRow();
        
        if(baris == -1){
            return;
        }
        
        String ID = Table.getValueAt(baris, 0).toString();
        IDDistributor.setText(ID);
        String Nama = Table.getValueAt(baris, 1).toString();
        NamaDistributor.setText(Nama);
        String Alamat = Table.getValueAt(baris, 2).toString();
        AlamatDistributor.setText(Alamat);
        String Kota = Table.getValueAt(baris, 3).toString();
        KotaAsal.setText(Kota);
        String Emaill = Table.getValueAt(baris, 4).toString();
        Email.setText(Emaill);
        String Telponn  = Table.getValueAt(baris, 5).toString();
        Telpon.setText(Telponn);
    }//GEN-LAST:event_TableMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int i = Table.getSelectedRow();
        
        if (i == -1){
            //tidak ada baris terseleksi
            JOptionPane.showMessageDialog(this, "Harap Pilih Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String ID = (String)model.getValueAt(i,0);
        
        try{
            Connection c = Koneksi.getKoneksi();
            
            String sql = "DELETE FROM tbldistributor WHERE IDDistributor = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, ID);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error");
        }finally{
            loadData();
            kosong();
        }

    }//GEN-LAST:event_DeleteActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        kosong(); 
        setEnabletrue(); 
        
    }//GEN-LAST:event_CancelActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"This application will be close \n if you press button OK","Information", JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION) 
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Distributor_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Distributor_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Distributor_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Distributor_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Distributor_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNew;
    private javax.swing.JTextArea AlamatDistributor;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Close;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField IDDistributor;
    private javax.swing.JTextField KotaAsal;
    private javax.swing.JTextField NamaDistributor;
    private javax.swing.JButton Save;
    private javax.swing.JTable Table;
    private javax.swing.JTextField Telpon;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

  

    
}
